### ISSUE TITLE
Unable to Install - gyp ERR! stack Error: make failed with exit code: 2

### ISSUE THREAD

**Issue by JasSmiths** [danielreiser/Homebridge-Simple-Garage-Door-Opener#6]
Hi,

I realise this plugin is quite old now but it appears that a new OS update has stopped the plugin from installing and its something I use every single day, I would be eternally grateful if you could take a look into this.

Logout output:

make: *** [rpio.target.mk:108: Release/obj.target/rpio/src/rpio.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.93-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpio@0.9.23 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rpio@0.9.23 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by EdgarLongin** [comment]
Hi JasSmiths ! 
As I had the same, i tried to install GPIO Device. It made me uinstall nodjs, and install it on version v10.19.0., and wiring pi 2.46 (2.50 have issues)
Don't forget to update npm on v6.14.4, 6.13 have issues with git.
Hope it will help you.
